services:
  bench_cloud:
    image: bench_cloud_img
    build:
      context: .
      dockerfile: Dockerfile-cloud
    env_file:
      - .env
    volumes:
      - ../api/llm_bench:/app/llm_bench
      - ./logs/:/var/log
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.config/gcloud:/root/.config/gcloud:ro
    network_mode: host
