services:
  bench_cloud:
    image: bench_cloud_img
    build:
      context: .
      dockerfile: Dockerfile-cloud
    env_file:
      - .env
    volumes:
      - ../api/llm_bench:/app/llm_bench
      - ./logs/:/var/log
      - /home/drose/.aws:/root/.aws
      - /home/drose/.config/gcloud:/root/.config/gcloud
    network_mode: host
