services:
  llm-benchmarking-api:
    build:
      context: .
      dockerfile: cloud/Dockerfile-cloud
    environment:
      # Core configuration
      - FASTAPI_PORT_CLOUD=5004
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log
      - LOG_TO_MONGO=true
      - USE_DATABASE_MODELS=true
      
      # MongoDB connection
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=llm-bench
      - MONGODB_COLLECTION_CLOUD=benchmarks_cloud
      
      # API Keys (set these in Coolify environment variables)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LAMBDA_API_KEY=${LAMBDA_API_KEY}
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
      - ANYSCALE_API_KEY=${ANYSCALE_API_KEY}
      
      # Provider base URLs (if needed)
      - TOGETHER_BASE_URL=https://api.together.xyz/v1
      - ANYSCALE_BASE_URL=https://api.endpoints.anyscale.com/v1
      
      # Azure endpoints (if using Azure)
      - AZURE_L70_POST_URL=${AZURE_L70_POST_URL:-}
      - AZURE_L70_API_KEY=${AZURE_L70_API_KEY:-}
      - AZURE_L13_POST_URL=${AZURE_L13_POST_URL:-}
      - AZURE_MISTRAL_L_API_KEY=${AZURE_MISTRAL_L_API_KEY:-}
      - AZURE_COHERE_CMD_R_PLUS_POST_URL=${AZURE_COHERE_CMD_R_PLUS_POST_URL:-}
      - AZURE_COHERE_CMD_R_PLUS_API_KEY=${AZURE_COHERE_CMD_R_PLUS_API_KEY:-}
      
      # RunPod endpoints (if using RunPod)
      - RUNPOD_L13_URL=${RUNPOD_L13_URL:-}
      
      # AWS Profile (for Bedrock)
      - AWS_PROFILE=${AWS_PROFILE:-default}
    
    ports:
      - "5004:5004"
    
    volumes:
      - ./cloud/logs:/var/log
      # Note: AWS and GCloud credentials will need to be handled via Coolify secrets/files
      # - /path/to/aws/credentials:/root/.aws:ro
      # - /path/to/gcloud/config:/root/.config/gcloud:ro