[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "llm_benchmarks"
version = "0.1.0"
description = "Benchmarking various LLMs inference speed"
authors = [
    "David Rose <david@drose.io>",
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
wandb = "^0.15.3"
transformers = "^4.29.2"
tqdm = "^4.65.0"
accelerate = "^0.19.0"
bitsandbytes = "^0.39.0"
ipywidgets = "^8.0.6"
pandas = "^2.0.2"
plotly = "^5.14.1"
nbformat = "^5.9.0"

[tool.black]
line-length = 120
