[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "llm-bench-api"
version = "0.1.0"
description = "Benchmarking various LLMs inference speed"
authors = [ "David Rose <david@drose.io>",]
license = "MIT"

[tool.black]
line-length = 120

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pymongo = "^4.6.0"
pynvml = "^11.5.0"
flask = "^3.0.0"
pytz = "^2024.1"
openai = "^1.12.0"
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
httpx = "^0.27.0"
typer = "^0.9.0"
python-dotenv = "^1.0.1"
